[build]
  command = "npm run build"
  publish = "build"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[context.production.environment]
  MONGODB_URI = `mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@cluster0.telw8lc.mongodb.net/Ads_FullStackAppDB?retryWrites=true&w=majority`
  
[context.deploy-preview.environment]
  MONGODB_URI = `mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@cluster0.telw8lc.mongodb.net/Ads_FullStackAppDB?retryWrites=true&w=majority`